sonar.projectKey=SyedaNoorBukhari_cohort-9-mern-11429-syeda
sonar.organization=syedanoorbukhari
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**
